//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plekhankov.DateBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Plekhankov_DemoEkzEntities : DbContext
    {
        private static Plekhankov_DemoEkzEntities _context;
        public Plekhankov_DemoEkzEntities()
            : base("name=Plekhankov_DemoEkzEntities")
        {
        }

        public static Plekhankov_DemoEkzEntities GetContext()
        {
            if (_context == null)
                _context = new Plekhankov_DemoEkzEntities();

            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Modeli_auto> Modeli_auto { get; set; }
        public virtual DbSet<nacenki> nacenki { get; set; }
        public virtual DbSet<Postavchiki> Postavchiki { get; set; }
        public virtual DbSet<postavka> postavka { get; set; }
        public virtual DbSet<priceKurant> priceKurant { get; set; }
        public virtual DbSet<Sdelka> Sdelka { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
