//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plekhankov.DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavchiki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postavchiki()
        {
            this.postavka = new HashSet<postavka>();
        }
    
        public int id { get; set; }
        public string name_firma { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string adress_site { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<postavka> postavka { get; set; }
    }
}
